### ISSUE TITLE
promisify

### ISSUE THREAD

**Issue by benjamingr** [ysmood/yaku#17]
Hey, if you want node usage, it would be immensely useful to support `promisify` natively. Without the library supporting it itself, it is impossible to make `promisify` comparably fast.

See bluebird's https://github.com/petkaantonov/bluebird/blob/master/src/promisify.js for inspiration :) 

I saw you already have a promisify.js file, but it is slow (uses a closure and `.slice`). 

A `promisifyAll` would also be immensely useful for server side use.

**Comment by ysmood** [comment]
Good point, will optimize the performance later. Besides you can try my another lib [nofs](https://github.com/ysmood/nofs).

**Comment by benjamingr** [comment]
Looks nice, in bluebird I just `Promise.promifiyAll(require("fs"))` and have a (close to) 0 overhead wrapper over fs, if I want to map/reduce etc I just use bluebird's utilities. 

Your code, uses Yaku's promisification in the test - I expect it to perform an order of magnitude slower if the OS caches the read files. It creates a closure and a bunch of other stuff whenever it reads a file :) 

When you optimize promisify I expect it to perform a lot better :) 

P.S I wonder - why do you have a `readJsonSync` function there? That's practially just a `require`

P.S 2 - why don't you chain in the tests https://github.com/ysmood/nofs/blob/1a0fe800548a8d58862b276c39fb7e960fe0fb41/test/basic.coffee#L51-L53 ? 

P.S 3 - this is just Array.prototype.every https://github.com/ysmood/nofs/blob/master/src/utils.coffee#L32-L37 

P.S 4 - https://github.com/ysmood/nofs/blob/master/src/utils.coffee#L32-L37 and this is Array.prototype.some

**Comment by ysmood** [comment]
> P.S I wonder - why do you have a readJsonSync function there? That's practially just a require

Because `require` will cache the file, `readJson` won't waste your memory.

> P.S 2 - why don't you chain in the tests

Coffeescript will auto chain them, or I mistook your meaning.

> P.S 3 - this is just Array.prototype.every
> Array.prototype.some

Old node don't supports them.

About your performance concern, I agree, but my 1 year experience told me it won't be the bottleneck of a large server side project, the IO itself will alway be the bottleneck. So we don't have to waste too much time on it. A better way is to push node support it natively, such as the browsers provide promise based `fetch` IO, all the file system operation should also support it internally.

**Comment by ysmood** [comment]
https://github.com/ysmood/yaku/commit/b336a4d85c7f16dd0135ff81b9e265afdc43ca2e#diff-1f0dd9d666794c01ded659349cb2512eR20

The promisify of Yaku is much less overhead now, the inline codes make the trick.
